server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/ry-vue?useSSL=false&serverTimezone=UTC
   driver-class-name: com.mysql.cj.jdbc.Driver
   username:  root
   password: 123456
  redis:
    host: 101.43.183.177
    port: 6379
    password: mk123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
logging:
  level:
    com.mk: debug
  charset:
    console: utf-8
#mapper??
mybatis-plus:
  mapper-locations:
    - classpath:com/mk/mapper/*.xml
